repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    - id: check-yaml
      stages: [pre-commit]
    - id: check-json
      stages: [pre-commit]
    - id: check-toml
      stages: [pre-commit]
    - id: check-merge-conflict
      stages: [pre-commit]
    - id: check-case-conflict
      stages: [pre-commit]
    - id: detect-private-key
      stages: [pre-commit]
