edition = "2021"
# stable
match_block_trailing_comma = true
max_width = 120
newline_style = "Windows"
use_field_init_shorthand = true
use_try_shorthand = true

# unstable
empty_item_single_line = false
enum_discrim_align_threshold = 20
fn_single_line = true
format_code_in_doc_comments = true
format_strings = true
imports_granularity = "crate"
imports_layout = "Vertical"
reorder_impl_items = true
struct_field_align_threshold = 20
# trailing_comma = "Always"
